version: "3.8"

services:

  recipe-recommender:
    build: ./recommender_api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://mxa5251:MRFeyxhj3jEnXdI4@recipe-recommender.rk0ehq4.mongodb.net/
      - DB_NAME=recipe-recommender
      - PORT=3000
    networks:
      - recipe-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports: ["27017:27017"]

networks:
  recipe-network:
    driver: bridge
