version: "3.8"

services:
  recipe-recommender:
    build: ./recommender_api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://mxa5251:MRFeyxhj3jEnXdI4@recipe-recommender.rk0ehq4.mongodb.net/
      - DB_NAME=recipe-recommender
      - PORT=5000
    networks:
      - recipe-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:6.0
    ports: ["27017:27017"]

networks:
  recipe-network:
    driver: bridge
