version: "3.8"

services:
  recipe-service:
    build: ./recipe-recommender
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://mxa5251:MRFeyxhj3jEnXdI4@recipe-recommender.rk0ehq4.mongodb.net/
      - DB_NAME=recipe-recommender
      - PORT=3000

  grocery-service:
    build: ./grocery-service
    ports:
      - "5001:5001"
    environment:
      - RECIPE_SERVICE_URL=http://recipe-service:3000
    depends_on:
      - recipe-service
