# recommender_api/do-app-spec.yaml
name: recommender-api
region: nyc1

services:
  - name: web
    image:
      registry_type: DOCKER_HUB
      repository: your-dockerhub-username/recommender_api
      tag: latest

    # The HTTP port your Flask app listens on
    http_port: 5000

    # How to start your app inside the container
    run_command: python -m app.app

    # Expose routes
    routes:
      - path: /

    # Health check against your new /health endpoint
    health_check:
      protocol: HTTP
      http_path: /health
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 3
      healthy_threshold: 1
      unhealthy_threshold: 2

    # Inject your Mongo connection info from DO secrets / envs
    envs:
      - key: MONGO_URI
        value: "${MONGO_URI}"
      - key: DB_NAME
        value: "${DB_NAME}"

    # Size & scale
    instance_count: 1
    instance_size_slug: professional-xs