name: recommender-api
region: nyc1

services:
  - name: api
    image:
      registry_type: DOCKER_HUB
      registry: jennifer1119
      repository: recommender_api
      tag: latest
      registry_credentials: "jennifer1119:dckr_pat_fxy]1ciZNwAyiLPzXCHZy8hFWuE"

    http_port: 3000

    health_check:
      http_path: "/health"
      port: 3000
      timeout_seconds: 5

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: MONGO_URI
        value: "mongodb+srv://mxa5251:MRFeyxhj3jEnXdI4@recipe-recommender.rk0ehq4.mongodb.net/"
      - key: DB_NAME
        value: "recipes"
      - key: PORT
        value: "3000"
