# recommender_api/do-app-spec.yaml
name: recommender-api
region: nyc1

services:
  - name: api
    # use your Docker Hub image
    image:
      registry_type: DOCKER_HUB
      registry: jennifer1119            # your Docker Hub username/org
      repository: recommender_api       # the repo name (no username prefix)
      tag: latest
      registry_credentials: "jennifer1119:dckr_pat_fxy]1ciZNwAyiLPzXCHZy8hFWuE"

    # expose the port your Flask app listens on
    http_port: 5000

    # health checking
    health_check:
      http_path: "/health" 
      port: 5000
      timeout_seconds: 5

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: MONGO_URI
        value: "mongodb+srv://doadmin:YOUR_REAL_PASSWORD@db-mongodb-nyc3-51746-9f87e3be.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-nyc3-51746"
      - key: DB_NAME
        value: "recipes"
