# recommender_api/do-app-spec.yaml
name: recommender-api
region: nyc1

services:
  - name: api
    # use your Docker Hub image
    image:
      registry_type: DOCKER_HUB
      registry: docker.io
      repository: jennifer1119/recommender_api
      tag: latest

    # expose the port your Flask app listens on
    http_port: 5000

    # health checking
    health_check:
      http_path: /
      port: 5000
      timeout_seconds: 5

    instance_count: 1
    instance_size_slug: basic-xxs

    envs:
      - key: MONGO_URI
        value: "mongodb+srv://doadmin:YOUR_REAL_PASSWORD@db-mongodb-nyc3-51746-9f87e3be.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=db-mongodb-nyc3-51746"
      - key: DB_NAME
        value: "recipes"
